routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('vehicle.index');
});

Route::name('vehicle.filter')->get('vehicle/filter/{brand}', 'VehicleController@filter');
Route::resource('vehicle', 'VehicleController');
Route::resource('client', 'ClientController');
Route::resource('order', 'OrderController');

app/Vehicle.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Vehicle extends Model
{
    protected $fillable = [
        // Relationships
        'owner_id',
        'engine_id',
        'policy_id',
        // Descriptive attributes
        'vin',
        'plate_number',
        'mileage',
        'number_of_seats',
        'number_of_doors',
        'colour',
        'brand',
        'model',
        'type',
        'subtype',
        // Timestamps
        'manufactured_at',
    ];

    protected $with = [
        'owner',
        'orders',
    ];

    protected $dates = [
        'manufactured_at',
    ];

    public function owner()
    {
        return $this->belongsTo(Client::class);
    }

    public function engine()
    {
        return $this->belongsTo(Engine::class);
    }

    public function policy()
    {
        return $this->belongsTo(Policy::class);
    }

    public function orders()
    {
        return $this->hasMany(Order::class);
    }

    public function order()
    {
        return $this->hasOne(Order::class);
    }

    public static function getTypes()
    {
        return collect([
            'car'        => 'Samochód',
            'truck'      => 'Ciężarówka',
            'motorcycle' => 'Motocykl',
        ]);
    }

    public function getNameAttribute()
    {
        return sprintf('%s %s', $this->brand, $this->model);
    }

    public function isBorrowed()
    {
        return $this->orders->sortByDesc('borrowed_from')->map(function ($order) {
            return $order->borrowed_to->isPast() ? false : $order->borrowed_from->isPast();
        })->filter()->isNotEmpty();
    }

    public function getBorrowerAttribute()
    {
        return $this->isBorrowed() ? $this->orders->sortByDesc('borrowed_from')->first()->borrower : false;
    }
}

app/Http/Controllers/VehicleController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\VehicleRequest;
use Illuminate\Http\Request;
use App\Vehicle;
use App\Engine;
use App\Client;

class VehicleController extends Controller
{
    public function index()
    {
        $brand = request()->get('brand');
        $vehicles = $brand ? Vehicle::where('brand', $brand)->paginate(20) : Vehicle::paginate(20);

        return view('vehicle.index', [
            'vehicles' => $vehicles,
        ]);
    }

    public function create()
    {
        $types   = Vehicle::getTypes()->prepend('-', '');
        $engines = Engine::all()->prepend('-', '');

        return view('vehicle.create', [
            'types'   => $types,
            'engines' => $engines,
        ]);
    }

    public function store(VehicleRequest $request)
    {
        $vehicle = $request->getVehicle();
        $vehicle->save();

        return redirect()->route('vehicle.index')->withFlash('Pomyślnie dodano pojazd');
    }

    public function show(Vehicle $vehicle)
    {
        return view('vehicle.show', [
            'vehicle' => $vehicle,
        ]);
    }

    public function edit(Vehicle $vehicle)
    {
        $clients = Client::all()->pluck('name', 'id')->prepend('-', '');

        return view('vehicle.edit', [
            'vehicle' => $vehicle,
            'clients' => $clients,
        ]);
    }

    public function update(Request $request, Vehicle $vehicle)
    {
        $vehicle->update($request->only([
            'owner_id',
            'mileage',
        ]));

        return redirect()->route('vehicle.index')->withFlash('Pomyślnie zaktualizowano pojazd');
    }

    public function destroy(Vehicle $vehicle)
    {
        $vehicle->delete();

        return redirect()->route('vehicle.index')->withFlash('Pomyślnie usunięto pojazd');
    }
}

resources/views/vehicle/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    {{ Breadcrumbs::render('vehicle.create') }}
    <div class="card">
        <div class="card-body">
            {{ Form::open([
                'route' => 'vehicle.store',
            ]) }}
            <div class="row">
                <div class="col-3">
                    <div class="form-group">
                        {{ Form::label('brand', 'Marka', [
                            'class' => 'form-label',
                        ]) }}
                        {{ Form::text('brand', null, [
                            'class'    => 'form-control',
                            'required' => 'required',
                        ]) }}
                    </div>
                </div>
                <div class="col-3">
                    <div class="form-group">
                        {{ Form::label('model', 'Model', [
                            'class' => 'form-label',
                        ]) }}
                        {{ Form::text('model', null, [
                            'class'    => 'form-control',
                            'required' => 'required',
                        ]) }}
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        {{ Form::label('type', 'Typ pojazdu', [
                            'class' => 'form-label',
                        ]) }}
                        {{ Form::select('type', $types, null, [
                            'class'    => 'form-control',
                            'required' => 'required',
                        ]) }}
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        {{ Form::label('vin', 'Numer VIN', [
                            'class' => 'form-label',
                        ]) }}
                        {{ Form::text('vin', null, [
                            'class'    => 'form-control',
                            'required' => 'required',
                        ]) }}
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        {{ Form::label('manufactured_at', 'Data produkcji', [
                            'class' => 'form-label',
                        ]) }}
                        {{ Form::date('manufactured_at', null, [
                            'class'    => 'form-control',
                            'required' => 'required',
                        ]) }}
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        {{ Form::label('plate_number', 'Numer rejestracyjny', [
                            'class' => 'form-label',
                        ]) }}
                        {{ Form::text('plate_number', null, [
                            'class'    => 'form-control',
                            'required' => 'required',
                        ]) }}
                    </div>
                </div>
                <div class="col-3">
                    <div class="form-group">
                        {{ Form::label('subtype', 'Typ nadwozia', [
                            'class' => 'form-label',
                        ]) }}
                        {{ Form::text('subtype', null, [
                            'class' => 'form-control',
                        ]) }}
                    </div>
                </div>
                <div class="col-3">
                    <div class="form-group">
                        {{ Form::label('colour', 'Kolor nadwozia', [
                            'class' => 'form-label',
                        ]) }}
                        {{ Form::text('colour', null, [
                            'class'    => 'form-control',
                            'required' => 'required',
                        ]) }}
                    </div>
                </div>
                <div class="col-3">
                    <div class="form-group">
                        {{ Form::label('number_of_doors', 'Liczba drzwi', [
                            'class' => 'form-label',
                        ]) }}
                        {{ Form::number('number_of_doors', null, [
                            'class'    => 'form-control',
                            'required' => 'required',
                        ]) }}
                    </div>
                </div>
                <div class="col-3">
                    <div class="form-group">
                        {{ Form::label('number_of_seats', 'Liczba miejsc', [
                            'class' => 'form-label',
                        ]) }}
                        {{ Form::number('number_of_seats', null, [
                            'class'    => 'form-control',
                            'required' => 'required',
                        ]) }}
                    </div>
                </div>
                <div class="col-3">
                    <div class="form-group">
                        {{ Form::label('engine_id', 'Silnik', [
                            'class' => 'form-label',
                        ]) }}
                        {{ Form::select('engine_id', $engines, null, [
                            'class'    => 'form-control',
                        ]) }}
                    </div>
                </div>
                <div class="col-3">
                    <div class="form-group">
                        {{ Form::label('mileage', 'Przebieg', [
                            'class' => 'form-label',
                        ]) }}
                        {{ Form::number('mileage', null, [
                            'class'    => 'form-control',
                            'required' => 'required',
                        ]) }}
                    </div>
                </div>
                @include('include.submit-btn', [
                    'text' => 'Dodaj »',
                ])
            </div>
            {{ Form::close() }}
        </div>
    </div>
</div>
@endsection

resources/views/vehicle/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    {{ Breadcrumbs::render('vehicle.edit', $vehicle) }}
    <div class="card">
        <div class="card-body">
            {{ Form::model($vehicle, [
                'route'  => ['vehicle.update', $vehicle],
                'method' => 'PUT',
            ]) }}
                <div class="row">
                    <div class="col-6">
                        <div class="form-group">
                            {{ Form::label('owner_id', 'Właściciel', [
                                'class' => 'form-label',
                            ]) }}
                            {{ Form::select('owner_id', $clients, null, [
                                'class'    => 'form-control',
                                'required' => 'required',
                            ]) }}
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            {{ Form::label('mileage', 'Przebieg', [
                                'class' => 'form-label',
                            ]) }}
                            {{ Form::number('mileage', null, [
                                'class'    => 'form-control',
                                'required' => 'required',
                            ]) }}
                        </div>
                    </div>
                    @include('include.submit-btn', [
                        'text' => 'Zapisz »',
                    ])
                </div>
            {{ Form::close() }}
        </div>
    </div>
</div>
@endsection

resources/views/vehicle/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    {{ Breadcrumbs::render('vehicle.index') }}
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="offset-2 col-4">
                    <div class="input-group">
                        {{ Form::text('brand', null, [
                            'class'        => 'form-control js-brand',
                            'placeholder'  => 'Wyszukaj po marce...',
                            'autocomplete' => 'off',
                        ]) }}
                        <span class="input-group-btn">
                            <a href="#" class="btn btn-info js-clear">Wyczyść</a>
                        </span>
                    </div>
                    <div class="dropdown">
                        <div class="dropdown-menu js-results"></div>
                    </div>
                </div>
                <div class="col-4">
                    <a class="btn btn-success btn-block" href="{{ route('vehicle.create') }}">Dodaj nowy samochód</a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th class="col-1">LP.</th>
                        <th>Marka/Model</th>
                        <th>Właściciel</th>
                        <th>Najemca</th>
                        <th>Data wynajmu</th>
                        <th class="col-1"></th>
                        <th class="col-1"></th>
                        <th class="col-1"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($vehicles as $vehicle)
                        <tr>
                            <td class="align-middle">{{ $loop->iteration }}</td>
                            <td class="align-middle">{{ $vehicle->brand }} {{ $vehicle->model}}</td>
                            <td class="align-middle">
                                @if($vehicle->owner)
                                    <a href="{{ route('client.show', $vehicle->owner) }}">
                                        <strong>{{ $vehicle->owner->name }}</strong>
                                    </a>
                                @endif
                            </td>
                            <td class="align-middle">
                                @if($vehicle->borrower)
                                    <a href="{{ route('client.show', $vehicle->borrower) }}">
                                        <strong>{{ $vehicle->borrower->name }}</strong>
                                    </a>
                                @endif
                            </td>
                            <td class="align-middle">
                                @if($vehicle->isBorrowed())
                                    <a href="{{ route('order.show', $vehicle->order) }}">
                                        <strong>{{ $vehicle->order->dates }}</strong>
                                    </a>
                                @endif
                            </td>
                            <td class="align-middle">
                                <a class="btn btn-warning btn-block" href="{{ route('vehicle.show', $vehicle) }}">Zobacz</a>
                            </td>
                            <td class="align-middle">
                                <a class="btn btn-primary btn-block" href="{{ route('vehicle.edit', $vehicle) }}">Edytuj</a>
                            </td>
                            <td class="align-middle">
                                <a class="btn btn-danger btn-block" href="{{ route('vehicle.destroy', $vehicle) }}">Usuń</a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>

            {{ $vehicles->links() }}
        </div>
    </div>
</div>
@endsection
@push('scripts')
<script type="text/javascript">
    $(document).ready(function () {
        const brand = $('.js-brand');
        const reset = $('.js-reset');
        brand.on('input', function () {
            const brand = $('.js-brand').val();
            axios.get(
                '/api/vehicle/index/' + brand
            ).then(function (response) {
                const data = response.data;
                const results = $('.js-results');
                results.empty();
                results.addClass('show');
                $.each(data, function (index, value) {
                    results.append(`<a class="dropdown-item" href="?brand=${index}">${index} (${value} wyników)</a>`);
                });
                if (results.is(':empty')) {
                    results.append('<span class="dropdown-item">Brak wyników</span>')
                }
            }).catch(function (error) {
                console.log(error);
            });
        });
        brand.keyup(function() {
            if (!this.value) {
                const results = $('.js-results');
                results.empty();
                results.removeClass('show');
            }
        });
        $('.js-clear').on('click', function () {
            const url = document.location.href;
            window.location.replace(url.split('?')[0]);
        });
    });
</script>
@endpush

resources/views/vehicle/show.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    {{ Breadcrumbs::render('vehicle.show', $vehicle) }}
    <div class="card">
        <div class="card-body">
            <table class="table table-striped table-hover">
                <tbody>
                    <tr>
                        <th class="col-4" scope="row">Marka</th>
                        <td>{{ $vehicle->brand }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Model</th>
                        <td>{{ $vehicle->model }}</td>
                    </tr>
                    <tr>
                        <th scope="row">VIN</th>
                        <td>{{ $vehicle->vin }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Numer rejestracyjny</th>
                        <td>{{ $vehicle->plate_number }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Data produkcji</th>
                        <td>{{ $vehicle->manufactured_at}}</td>
                    </tr>
                    <tr>
                        <th scope="row">Przebieg</th>
                        <td>{{ $vehicle->mileage }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Kolor</th>
                        <td>{{ $vehicle->colour }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Liczba drzwi / miejsc</th>
                        <td>{{ $vehicle->number_of_doors }} / {{ $vehicle->number_of_seats }}</td>
                    </tr>
                </tbody>
            </table>
            <div class="row">
                <div class="offset-4 col-4">
                    <a class="btn btn-primary btn-block" href="{{ route('vehicle.edit', $vehicle) }}">Edytuj »</a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection