routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('vehicle.index');
});

Route::name('vehicle.filter')->get('vehicle/filter/{brand}', 'VehicleController@filter');
Route::resource('vehicle', 'VehicleController');
Route::resource('client', 'ClientController');
Route::resource('order', 'OrderController');

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    protected $fillable = [
        'first_name',
        'last_name',
        'pesel',
        'address_1',
        'address_2',
        'address_3',
        'postal_code',
        'city',
        'email',
        'phone_number',
    ];

    public function vehicles()
    {
        return $this->hasMany(Vehicle::class, 'owner_id');
    }

    public function orders()
    {
        return $this->hasMany(Order::class, 'borrower_id');
    }

    public function getNameAttribute()
    {
        return sprintf('%s %s', $this->first_name, $this->last_name);
    }

    public function getAddressAttribute()
    {
        $pattern = $this->address_3 ? '%s %s/%s' : '%s %s';

        return sprintf($pattern, $this->address_1, $this->address_2, $this->address_3);
    }
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ClientRequest;
use Illuminate\Http\Request;
use App\Client;

class ClientController extends Controller
{
    public function index()
    {
        $clients = Client::paginate(20);

        return view('client.index', [
            'clients' => $clients,
        ]);
    }

    public function create()
    {
        return view('client.create');
    }

    public function store(ClientRequest $request)
    {
        $client = $request->getClient();
        $client->save();

        return redirect()->route('client.index')->withFlash('Pomyślnie dodano klienta');
    }

    public function show(Client $client)
    {
        return view('client.show', [
            'client' => $client,
        ]);
    }

    public function edit(Client $client)
    {
        return view('client.edit', [
            'client' => $client,
        ]);
    }

    public function update(ClientRequest $request, Client $client)
    {
        $client->update($request->getData());

        return redirect()->route('client.index')->withFlash('Pomyślnie zaktualizowano klienta');
    }

    public function destroy(Client $client)
    {
        $client->delete();

        return redirect()->route('client.index')->withFlash('Pomyślnie usunięto klienta');
    }
}

resources/views/client/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    {{ Breadcrumbs::render('client.create') }}
    <div class="card">
        <div class="card-body">
            {{ Form::open([
                'route' => 'client.store',
            ]) }}
                <div class="row">
                    @include('client.form-inputs')
                    @include('include.submit-btn', [
                        'text' => 'Dodaj »',
                    ])
                </div>
            {{ Form::close() }}
        </div>
    </div>
</div>
@endsection

resources/views/client/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    {{ Breadcrumbs::render('client.edit', $client) }}
    <div class="card">
        <div class="card-body">
            {{ Form::model($client, [
                'route'  => ['client.update', $client],
                'method' => 'PUT',
            ]) }}
                <div class="row">
                    @include('client.form-inputs')
                    @include('include.submit-btn', [
                        'text' => 'Zapisz »',
                    ])
                </div>
            {{ Form::close() }}
        </div>
    </div>
</div>
@endsection

resources/views/client/form-inputs.blade.php
<div class="col-6">
    <div class="form-group">
        {{ Form::label('first_name', 'Imię', [
            'class' => 'form-label',
        ]) }}
        {{ Form::text('first_name', null, [
            'class'    => 'form-control',
            'required' => 'required',
        ]) }}
    </div>
</div>
<div class="col-6">
    <div class="form-group">
        {{ Form::label('last_name', 'Nazwisko', [
            'class' => 'form-label',
        ]) }}
        {{ Form::text('last_name', null, [
            'class'    => 'form-control',
            'required' => 'required',
        ]) }}
    </div>
</div>
<div class="col-6">
    <div class="form-group">
        {{ Form::label('pesel', 'PESEL', [
            'class' => 'form-label',
        ]) }}
        {{ Form::text('pesel', null, [
            'class'    => 'form-control',
            'required' => 'required',
        ]) }}
    </div>
</div>
<div class="col-3">
    <div class="form-group">
        {{ Form::label('email', 'Adres email', [
            'class' => 'form-label',
        ]) }}
        {{ Form::text('email', null, [
            'class' => 'form-control',
        ]) }}
    </div>
</div>
<div class="col-3">
    <div class="form-group">
        {{ Form::label('phone_number', 'Numer kontaktowy', [
            'class' => 'form-label',
        ]) }}
        {{ Form::text('phone_number', null, [
            'class' => 'form-control',
        ]) }}
    </div>
</div>
<div class="col-3">
    <div class="form-group">
        {{ Form::label('postal_code', 'Kod pocztowy', [
            'class' => 'form-label',
        ]) }}
        {{ Form::text('postal_code', null, [
            'class'    => 'form-control',
            'required' => 'required',
        ]) }}
    </div>
</div>
<div class="col-3">
    <div class="form-group">
        {{ Form::label('city', 'Miasto', [
            'class' => 'form-label',
        ]) }}
        {{ Form::text('city', null, [
            'class'    => 'form-control',
            'required' => 'required',
        ]) }}
    </div>
</div>
<div class="col-3">
    <div class="form-group">
        {{ Form::label('address_1', 'Ulica', [
            'class' => 'form-label',
        ]) }}
        {{ Form::text('address_1', null, [
            'class'    => 'form-control',
            'required' => 'required',
        ]) }}
    </div>
</div>
<div class="col-2">
    <div class="form-group">
        {{ Form::label('address_2', 'Nr domu', [
            'class' => 'form-label',
        ]) }}
        {{ Form::text('address_2', null, [
            'class'    => 'form-control',
            'required' => 'required',
        ]) }}
    </div>
</div>
<div class="col-1">
    <div class="form-group">
        {{ Form::label('address_3', 'Nr lokalu', [
            'class' => 'form-label',
        ]) }}
        {{ Form::text('address_3', null, [
            'class' => 'form-control',
        ]) }}
    </div>
</div>

resources/views/client/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    {{ Breadcrumbs::render('client.index') }}
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="offset-4 col-md-4">
                    <a class="btn btn-success btn-block" href="{{ route('client.create') }}">Dodaj nowego klienta</a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th class="col-1">LP.</th>
                        <th>Imię i nazwisko</th>
                        <th>Adres</th>
                        <th>Kontakt mailowy</th>
                        <th>Kontakt telefoniczny</th>
                        <th class="col-1"></th>
                        <th class="col-1"></th>
                        <th class="col-1"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($clients as $client)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $client->name }}</td>
                            <td>{{ $client->address }}</td>
                            <td>{{ $client->email }}</td>
                            <td>{{ $client->phone_number }}</td>
                            <td>
                                <a class="btn btn-warning btn-block" href="{{ route('client.show', $client) }}">Zobacz</a>
                            </td>
                            <td>
                                <a class="btn btn-primary btn-block" href="{{ route('client.edit', $client) }}">Edytuj</a>
                            </td>
                            <td>
                                <a class="btn btn-danger btn-block" href="{{ route('client.destroy', $client) }}">Usuń</a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>

            {{ $clients->links() }}
        </div>
    </div>
</div>
@endsection

resources/views/client/show.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    {{ Breadcrumbs::render('client.show', $client) }}
    <div class="card">
        <div class="card-body">
            <h1 class="text-center">{{ $client->name }}</h1>
            @if($client->vehicles->isNotEmpty())
                <table class="table table-striped table-hover">
                    <i>Właściciel poniższych samochodów</i>
                    <thead>
                        <tr>
                            <th>Marka i model</th>
                            <th>Data produkcji</th>
                            <th>Numer rejestracyjny</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($client->vehicles as $vehicle)
                            <tr>
                                <td>
                                    <a href="{{ route('vehicle.show', $vehicle) }}">
                                        <strong>{{ $vehicle->name }}</strong>
                                    </a>
                                </td>
                                <td>{{ $vehicle->manufactured_at }}</td>
                                <td>{{ $vehicle->plate_number }}</td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            @endif
            @if($client->orders->isNotEmpty())
                <table class="table table-striped table-hover">
                    <i>Zamówienia</i>
                    <thead>
                        <tr>
                            <th>Marka i model</th>
                            <th>Numer rejestracyjny</th>
                            <th>Data wynajmu</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($client->orders as $order)
                            <tr>
                                <td>
                                    <a href="{{ route('vehicle.show', $order->vehicle) }}">
                                        <strong>{{ $order->vehicle->name }}</strong>
                                    </a>
                                </td>
                                <td>{{ $order->vehicle->plate_number }}</td>
                                <td>{{ $order->dates }}</td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            @endif
            <div class="row">
                <div class="offset-4 col-4">
                    <a class="btn btn-primary btn-block" href="{{ route('client.edit', $client) }}">Edytuj »</a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection