routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('vehicle.index');
});

Route::name('vehicle.filter')->get('vehicle/filter/{brand}', 'VehicleController@filter');
Route::resource('vehicle', 'VehicleController');
Route::resource('client', 'ClientController');
Route::resource('order', 'OrderController');

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>Car-Rental</title>
        <link rel="shortcut icon" href="https://assets.gitlab-static.net/uploads/-/system/project/avatar/5702454/car.png" type="image/x-icon">
        <link rel="icon" href="https://assets.gitlab-static.net/uploads/-/system/project/avatar/5702454/car.png" type="image/x-icon">

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">
        @yield('assets')
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Car-Rental</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"  aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('vehicle.index') }}">Samochody</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('client.index') }}">Klienci</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('order.index') }}">Wypożyczalnia</a>
                    </li>
                </ul>
            </div>
        </nav>
        <div class="container text-center">
            @include('flash::message')
        </div>
        @yield('content')
        <script src="{{ asset('js/app.js') }}" charset="utf-8"></script>
        <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
        @stack('scripts')
    </body>
</html>