routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('vehicle.index');
});

Route::name('vehicle.filter')->get('vehicle/filter/{brand}', 'VehicleController@filter');
Route::resource('vehicle', 'VehicleController');
Route::resource('client', 'ClientController');
Route::resource('order', 'OrderController');

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Order extends Model
{
    protected $fillable = [
        'borrower_id',
        'vehicle_id',
        'borrowed_from',
        'borrowed_to',
    ];

    protected $dates = [
        'borrowed_from',
        'borrowed_to',
    ];

    public function borrower()
    {
        return $this->belongsTo(Client::class);
    }

    public function vehicle()
    {
        return $this->belongsTo(Vehicle::class);
    }

    public function getDatesAttribute()
    {
        return sprintf('%s - %s', $this->borrowed_from, $this->borrowed_to);
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\OrderRequest;
use Illuminate\Http\Request;
use App\Vehicle;
use App\Client;
use App\Order;

class OrderController extends Controller
{
    public function index()
    {
        $orders = Order::paginate(20);

        return view('order.index', [
            'orders' => $orders,
        ]);
    }

    public function create()
    {
        $vehicles = Vehicle::all()->pluck('name', 'id')->prepend('-', '');
        $clients  = Client::all()->pluck('name', 'id')->prepend('-', '');

        return view('order.create', [
            'vehicles' => $vehicles,
            'clients'  => $clients,
        ]);
    }

    public function store(OrderRequest $request)
    {
        $order = $request->getOrder();
        $order->save();

        return redirect()->route('order.index')->withFlash('Pomyślnie dodano zamówienie');
    }

    public function show(Order $order)
    {
        return view('order.show', [
            'order' => $order,
        ]);
    }

    public function edit(Order $order)
    {
        $vehicles = Vehicle::all()->pluck('name', 'id')->prepend('-', '');
        $clients  = Client::all()->pluck('name', 'id')->prepend('-', '');

        return view('order.edit', [
            'vehicles' => $vehicles,
            'clients'  => $clients,
            'order'    => $order,
        ]);;
    }

    public function update(Request $request, Order $order)
    {
        $order->update($request->getData());

        return redirect()->route('order.index')->withFlash('Pomyślnie zaktualizowano zamówienie');
    }

    public function destroy(Order $order)
    {
        $order->delete();

        return redirect()->route('order.index')->withFlash('Pomyślnie usunięto zamówienie');
    }
}

resources/views/order/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    {{ Breadcrumbs::render('order.create') }}
    <div class="card">
        <div class="card-body">
            {{ Form::open([
                'route' => 'order.store',
            ]) }}
                <div class="row">
                    @include('order.inputs')
                    <div class="offset-3 col-3">
                        <a class="btn btn-primary btn-block" href="{{ URL::previous() }}">« Wróć</a>
                    </div>
                    <div class="col-3">
                        {{ Form::button('Dodaj »', [
                            'class' => 'btn btn-success btn-block',
                            'type'  => 'submit',
                        ]) }}
                    </div>
                </div>
            {{ Form::close() }}
        </div>
    </div>
</div>
@endsection

resources/views/order/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    {{ Breadcrumbs::render('order.edit', $order) }}
    <div class="card">
        <div class="card-body">
            {{ Form::model($order, [
                'route'  => ['order.update', $order],
                'method' => 'PUT',
            ]) }}
                <div class="row">
                    @include('order.inputs')
                    @include('include.submit-btn', [
                        'text' => 'Zapisz »',
                    ])
                </div>
            {{ Form::close() }}
        </div>
    </div>
</div>
@endsection

resources/views/order/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    {{ Breadcrumbs::render('order.index') }}
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="offset-4 col-md-4">
                    <a class="btn btn-success btn-block" href="{{ route('order.create') }}">Dodaj nowe zamówienie</a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th class="col-1">LP.</th>
                        <th>Najemca</th>
                        <th>Samochód</th>
                        <th>Wynajem od dnia</th>
                        <th>Wynajem do dnia</th>
                        <th class="col-1"></th>
                        <th class="col-1"></th>
                        <th class="col-1"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($orders as $order)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>
                                <a href="{{ route('client.show', $order->borrower) }}">
                                    <strong>{{ $order->borrower->name }}</strong>
                                </a>
                            </td>
                            <td>
                                <a href="{{ route('vehicle.show', $order->vehicle) }}">
                                    <strong>{{ $order->vehicle->name }}</strong>
                                </a>
                            </td>
                            <td>{{ $order->borrowed_to }}</td>
                            <td>{{ $order->borrowed_from }}</td>
                            <td>
                                <a class="btn btn-warning btn-block" href="{{ route('order.show', $order) }}">Zobacz</a>
                            </td>
                            <td>
                                <a class="btn btn-primary btn-block" href="{{ route('order.edit', $order) }}">Edytuj</a>
                            </td>
                            <td>
                                <a class="btn btn-danger btn-block" href="{{ route('order.destroy', $order) }}">Usuń</a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>

            {{ $orders->links() }}
        </div>
    </div>
</div>
@endsection

resources/views/order/inputs.blade.php
<div class="col-6">
    <div class="form-group">
        {{ Form::label('vehicle_id', 'Pojazd', [
            'class' => 'form-label',
        ]) }}
        {{ Form::select('vehicle_id', $vehicles, null, [
            'class'    => 'form-control',
            'required' => 'required',
        ]) }}
    </div>
</div>
<div class="col-6">
    <div class="form-group">
        {{ Form::label('borrower_id', 'Najemca', [
            'class' => 'form-label',
        ]) }}
        {{ Form::select('borrower_id', $clients, null, [
            'class'    => 'form-control',
            'required' => 'required',
        ]) }}
    </div>
</div>
<div class="col-6">
    <div class="form-group">
        {{ Form::label('borrowed_from', 'Wynajem od', [
            'class' => 'form-label',
        ]) }}
        <div class="input-group">
            {{ Form::date('borrowed_from[date]', null, [
                'class'    => 'form-control',
                'required' => 'required',
            ]) }}
            <div class="input-group-addon">
                {{ Form::time('borrowed_from[time]', null, [
                    'class'    => 'form-control',
                    'required' => 'required',
                ]) }}
            </div>
        </div>
    </div>
</div>
<div class="col-6">
    <div class="form-group">
        {{ Form::label('borrowed_to', 'Wynajem do', [
            'class' => 'form-label',
        ]) }}
        <div class="input-group">
            {{ Form::date('borrowed_to[date]', null, [
                'class'    => 'form-control',
                'required' => 'required',
            ]) }}
            <div class="input-group-addon">
                {{ Form::time('borrowed_to[time]', null, [
                    'class'    => 'form-control',
                    'required' => 'required',
                ]) }}
            </div>
        </div>
    </div>
</div>

resources/views/order/show.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    {{ Breadcrumbs::render('order.show', $order) }}
    <div class="card">
        <div class="card-body">
        </div>
    </div>
</div>
@endsection